version: "3.7"

services:

  mongo:
    restart: "unless-stopped"
    image: mongo:bionic
    container_name: "migracao-mongodb"
    volumes:
    - mongo-data:/data/db
    ports:
      - 27117:27017
    env_file:
    - ./mongo.env
    networks:
    - databases-network


volumes:
  mongo-data: {}

networks:
    databases-network:
      driver: bridge
